version: "3.9"
services:
  backend:
    env_file:
      - .env
    build:
      context: ./backend
    container_name: fastapi-api
    ports:
      - 8080:8080
  frontend:
    build:
      context: ./frontend
    container_name: vue-ui
    ports:
      - 80:80
